### PR TITLE
[WIP] Fixes

### PR DESCRIPTION
**Pull request by planetis-m**

### CODE REVIEW

**Comment by planetis-m** [comment]
needs a way to distinguish `NimNodeKind`s from other, or did I broke it?

**Comment by planetis-m** [comment]
Actually no it's ready. For me to improve it, I would rewrite it.

**Comment by alehander92** [comment]
is it ready? I am not really actively maintaining it, but I might accept PR-s like that, thank you!

**Comment by planetis-m** [comment]
Yes, it's ready

**Comment by alehander92** [comment]
Ok! thanks <3

**Comment by planetis-m** [comment]
Thank you!

**Pull request merged**
